# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tempr.Cli
PackageVersion: 0.9.11
InstallerType: zip
NestedInstallerType: portable
Commands:
  - tempr
Installers:
  - Architecture: x64
    InstallerUrl: https://temprhq.io/cli/v0.9.11/tempr-0.9.11-win-x64.zip
    InstallerSha256: 0d7db6275e293172a8ee5ccf1f2f84da9e55ecd6c0fba5e94b97ec2609b36224
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
  - Architecture: arm64
    InstallerUrl: https://temprhq.io/cli/v0.9.11/tempr-0.9.11-win-arm64.zip
    InstallerSha256: 7bc8aea0160cd0de207c70669425eb8777dd3164460582b7635ccadbe64334cd
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
ManifestType: installer
ManifestVersion: 1.12.0
