# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tempr.Cli
PackageVersion: 0.9.12
InstallerType: zip
NestedInstallerType: portable
Commands:
  - tempr
Installers:
  - Architecture: x64
    InstallerUrl: https://temprhq.io/cli/v0.9.12/tempr-0.9.12-win-x64.zip
    InstallerSha256: 253173514e5eac4ba04e1b5797d18ebf01cb1c5ff73d1e03ec01e78bb069cd31
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
  - Architecture: arm64
    InstallerUrl: https://temprhq.io/cli/v0.9.12/tempr-0.9.12-win-arm64.zip
    InstallerSha256: 74d7f263541ed4ed301ee417a7e1b15c1e02cae0a7c6bfd233e9092ec18dd5cb
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
ManifestType: installer
ManifestVersion: 1.12.0
