# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tempr.Cli
PackageVersion: 0.9.15
InstallerType: zip
NestedInstallerType: portable
Commands:
  - tempr
Installers:
  - Architecture: x64
    InstallerUrl: https://temprhq.io/cli/v0.9.15/tempr-0.9.15-win-x64.zip
    InstallerSha256: b9d089901a5256b524f3f67d2b4d173bbee8419f164274b8a2e27f0fb18acccf
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
  - Architecture: arm64
    InstallerUrl: https://temprhq.io/cli/v0.9.15/tempr-0.9.15-win-arm64.zip
    InstallerSha256: 83ed35742bd2ec7e3030f1b3b8a4efd57bfdf4cf7517da88a21dce08faa1e13b
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
ManifestType: installer
ManifestVersion: 1.12.0
