# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tempr.Cli
PackageVersion: 0.9.13
InstallerType: zip
NestedInstallerType: portable
Commands:
  - tempr
Installers:
  - Architecture: x64
    InstallerUrl: https://temprhq.io/cli/v0.9.13/tempr-0.9.13-win-x64.zip
    InstallerSha256: 7638eb2d7a541b898c30fc625cd9e2b6ed12795a0a5c255d8aaec98df4de0d29
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
  - Architecture: arm64
    InstallerUrl: https://temprhq.io/cli/v0.9.13/tempr-0.9.13-win-arm64.zip
    InstallerSha256: d2d107060511c7a839229692255f63117f0003c710e553de703641483da0287e
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
ManifestType: installer
ManifestVersion: 1.12.0
