# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tempr.Cli
PackageVersion: 0.9.14
InstallerType: zip
NestedInstallerType: portable
Commands:
  - tempr
Installers:
  - Architecture: x64
    InstallerUrl: https://temprhq.io/cli/v0.9.14/tempr-0.9.14-win-x64.zip
    InstallerSha256: d74c881bd8805d7ae26bb45ba78fcfefb653551b7f1dd2534284badc8b22e485
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
  - Architecture: arm64
    InstallerUrl: https://temprhq.io/cli/v0.9.14/tempr-0.9.14-win-arm64.zip
    InstallerSha256: 8b718daaac1bfad1ebfd4e0e40d229448a7049dfe1be04d22ef5a9eca026ecff
    NestedInstallerFiles:
      - RelativeFilePath: tempr.exe
        PortableCommandAlias: tempr
ManifestType: installer
ManifestVersion: 1.12.0
